### ISSUE TITLE
Spring Batch 2.2.x Configuration

### ISSUE THREAD

**Issue by michaelbrzycki** [johnrengelman/grails-spring-batch#20]
How do I configure the spring dependencies to allow use with spring batch versions greater than 2.2.0? I've been running into this error in my naive attempts:
"java.lang.NoClassDefFoundError: org/springframework/core/type/classreading/AnnotationMetadataReadingVisitor"

My grails version is 2.2.1 but can go up if need be.

**Comment by danieldbower** [comment]
Spring Batch versions greater than 2.2.0 require a higher version of Spring than what Grails 2.2 supplies.    Upgrading to a later version of Spring Batch would require upgrading the plugin for a later version of Grails.  I imagine that will happen for Grails 3.0 at some point in the next year.  I'll likely upgrade it with the first Grails 3 project that I get to work on.

**Comment by danieldbower** [comment]
I should note that there is a branch by @xmlking grails-spring-batch that is using Grails 2.4.4 and Spring Batch 3.0.2.RELEASE.  I've not tested/used it yet though.
