### ISSUE TITLE
After WAR job beans are not getting loaded...

### ISSUE THREAD

**Issue by VigneshwaranK** [johnrengelman/grails-spring-batch#27]
After I did build war , job beans are not getting loaded and throwing null pointer exception for me , then I looked for reason , then I found  this code 
     def loadBatchConfig = { ->
        loadBeans 'classpath*:/batch/*BatchConfig.groovy'
    }
 in SpringBatchGrailsPlugin.groovy , which looks for BatchConfig files in batch/ directory but while creating war those directory are not getting created , so I did  a work around as given below 
        "eventCreateWarStart = { warName, stagingDir -> 
                      ant.move(todir:"${stagingDir}/WEB-INF/classes/batch"){
				fileset(dir:"${basedir}/grails-app/batch", includes:"**/*BatchConfig.groovy") }}" ,

Is this excepted or is it bug ???

**Comment by danieldbower** [comment]
Issue #29 and this one are duplicates.  Closing this one.
